name: Java CI

on: [push]

jobs:
  build:
    name: build with tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -s .mvn/settings.xml -B clean package