name: Java CI

on: [push]

jobs:
  build:
    name: build with tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Configure deployment
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "dev-toolbox.org", "url": "https://maven.dev-toolbox.org/main" }]'
      - name: Build with Maven
        run: mvn -B clean package
